version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "task4"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    command: postgres -c tcp_keepalives_idle=60 -c tcp_keepalives_interval=60 -c tcp_keepalives_count=60
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data